### ISSUE TITLE
terraform apply error

### ISSUE THREAD

**Issue by Xyders** [gbrembati/terraform-cloudguard-k8s-protection#1]
Hi, this is Scott from Check Point APAC region. It's a wonderful project you created, but I run into an error when doing terraform apply as follow:
│ Error: Attempt to index null value
│
│   on azure-aks-main.tf line 22, in resource "azurerm_dns_a_record" "juiceshop-appsec-dns-record":
│   22:   records             = ["${data.kubernetes_service.ckp-appsec-controller.status.0.load_balancer.0.ingress.0.ip}"]
│     ├────────────────
│     │ data.kubernetes_service.ckp-appsec-controller.status is null
│
│ This value is null, so it does not have any indices.

You defined data.kubernetes_service.ckp-appsec-controller, but I didn't find where is that resource defined? Is it a version problem? Can you give me some advice?

**Comment by gbrembati** [comment]
Hi Scott,
Great to hear from you.
The Appsec helm chart creates the ingress controller and service for it,
the data resource is the way I fetch from the service that was created in
Azure for the LB IP. I found this issue before, but I forgot to update it,
it's now public.

The new chart (ver 4.1.4) changed the default naming schema, the data
resource was defined to look for something ending with
"-cpappsec-controller" but now the name is different so it can't fetch it
(so the resource is null).

[image: image.png]

This change is live in my repo, so you should be all set now.
Thanks for the heads up, let me know how it goes.

**Comment by Xyders** [comment]
Great, now it can be created without problem. Thank you!
